apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        project: expense
    spec:
      # init container run before main containers run. if it is failed, then main containers will not run
      initContainers:
      - name: mysql-check
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mysql; do echo waiting for myservice; sleep 2; done"]

      containers:
      - name: backend
        image: mlndockerhub/backend:v1
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe: # /health using httpGet
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: backend

---
apiVersion: v1 
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
    project: expense
  ports:
  - name: backend
    protocol: "TCP"
    port: 8080
    targetPort: 8080