apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        project: expense
    spec:
      containers:
      - name: backend
        image: mlndockerhub/backend:v1
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe: # /health using httpGet
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3

---
apiVersion: v1 
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
    project: expense
  ports:
  - name: backend
    protocol: "TCP"
    port: 8080
    targetPort: 8080