apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels: 
    app: mysql
    tier: db
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: mlndockerhub/mysql:v1
        readinessProbe: # readiness probe
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe: # liveness probe
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: v1 
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql
    protocol: "TCP"
    port: 3306
    targetPort: 3306