apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels: 
    app: mysql
    tier: db
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: mlndockerhub/mysql:v1
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 10